#!/bin/bash

FILE="data.json"

NAME=$(jq -r '.name' $FILE)
HEIGHT=$(jq -r '.height' $FILE)
WEIGHT=$(jq -r '.weight' $FILE)
TYPE=$(jq -r '.types[0].type.name' $FILE)

# Convert units
HEIGHT_M=$(awk "BEGIN {printf \"%.1f\", $HEIGHT/10}")
WEIGHT_KG=$(awk "BEGIN {printf \"%.1f\", $WEIGHT/10}")

# Print human-readable info
echo "${NAME^} is of type ${TYPE^}, weighs ${WEIGHT_KG}kg, and is ${HEIGHT_M}m tall."
