#!/bin/bash

FILE="data.json"

# Extract data using jq
NAME=$(jq -r '.name' $FILE)
HEIGHT=$(jq -r '.height' $FILE)
WEIGHT=$(jq -r '.weight' $FILE)
TYPE=$(jq -r '.types[0].type.name' $FILE)

# Convert units and format integers
HEIGHT_M=$(awk "BEGIN {h=$HEIGHT/10; if(h==int(h)) h=int(h); printf \"%s\", h}")
WEIGHT_KG=$(awk "BEGIN {w=$WEIGHT/10; if(w==int(w)) w=int(w); printf \"%s\", w}")

# Capitalize using sed
NAME=$(echo $NAME | sed 's/.*/\u&/')
TYPE=$(echo $TYPE | sed 's/.*/\u&/')

# Print formatted output
echo "$NAME is of type $TYPE, weighs ${WEIGHT_KG}kg, and is ${HEIGHT_M}m tall."
